### ISSUE TITLE
set_col_width and set_row_height don't work

### ISSUE THREAD

**Issue by RustyNixieTube** [thscharler/spreadsheet-ods#1]
**Cargo.toml:**
```
[dependencies]
spreadsheet-ods = "0.4.0"
color-rs = "0.5.0"
```
**main.rs:**
```
use spreadsheet_ods::*;
use spreadsheet_ods::style::*;

fn main() {
    let output_file = std::path::Path::new("test.ods");

    let mut wb = WorkBook::new();

    let mut style = Style::new_cell_style("Square style", "");
    style.col_mut().set_col_width(Length::Cm(10.0));
    style.row_mut().set_row_height(Length::Cm(10.0));
    wb.add_style(style);

    let mut sheet = spreadsheet_ods::Sheet::new_with_name("test");
    sheet.cell_mut(1, 1).set_style("Square style");
    wb.push_sheet(sheet);

    if let Err(x) = spreadsheet_ods::write_ods(&wb, output_file) {
        println!("Error: {}", x)
    }
    
}
```
**result(compressed because GitHub doesn't support ods):** [test.zip](https://github.com/thscharler/spreadsheet-ods/files/4884064/test.zip)

**Comment by thscharler** [comment]
I see, should have put a few locks in place. 
style.col_mut() is only useful for Style::new_col_style() and style.row_mut() for Style::new_row_style(). 

The way to do this is

    sheet.set_row_height(&mut wb, 1, cm!(10));
    sheet.set_col_width(&mut wb, 1, cm!(10));
    sheet.set_value(1, 1, "");

The first two calls create the correct styles, and set_value assures that the cell is actually written to the file. 

This works better, but there seems to be another issue. The row height is set for the first row too. Will check where that comes from.

**Comment by thscharler** [comment]
0.4.1 fixes the write bug. 

There is an alternative usage

  sheet.set_row_height(&mut wb, 1, cm!(10));
  sheet.set_col_width(&mut wb, 1, cm!(10));
  **sheet.set_value(1, 1, ());**

It is still necessary to set a cell value (or formula, or cell-style). 
All row/column styles beyond the maximum cell are discarded.
