### ISSUE TITLE
date / currency value formats not working; xmlns:number missing in root elment

### ISSUE THREAD

**Issue by rbi** [thscharler/spreadsheet-ods#22]
# how to reproduce
* speadsheet-ods 0.5.2
* Try to format a NaveDateTime value as date only

~~~
use std::path::Path;
use std::error::Error;

use chrono::{NaiveDateTime, NaiveDate, NaiveTime};
use spreadsheet_ods::*;

pub fn write() -> Result<(), impl Error> {

    let mut work_book = WorkBook::new();

    let date_format = work_book.add_format(format::create_date_dmy_format("date_format"));
    let date_style = work_book.add_cellstyle(CellStyle::new("date", &date_format));

    let mut sheet = Sheet::new_with_name("some sheet");
    let value = NaiveDateTime::new(NaiveDate::from_ymd(2021, 05, 02), NaiveTime::from_hms(12,23,24));
    sheet.set_styled_value(0, 0, value, &date_style);

    work_book.push_sheet(sheet);
    write_ods(&work_book, Path::new("out.ods"))
}
~~~

# what happened
* In the resulting spread sheet the date and time are visible
* [out.ods](https://github.com/thscharler/spreadsheet-ods/files/6411154/out.ods)

# what should happen
* In the resulting spread sheet only the date should be displayed

# analysis
The XML namespace ` xmlns:number="urn:oasis:names:tc:opendocument:xmlns:datastyle:1.0"` seams missing from `content.xml`. This is what xmllint says when formatting the file.

~~~
content.xml:2: namespace error : Namespace prefix number for style on day is not defined
tyle><number:date-style style:name="date_format"><number:day number:style="long"
~~~

Manually adding ` xmlns:number="urn:oasis:names:tc:opendocument:xmlns:datastyle:1.0"` to `content.xml` and putting it back into `out.ods` seams to fix the issue.

**Comment by thscharler** [comment]
Yes, I notized this too, just forgot to publish a patch. Done.
