### ISSUE TITLE
Request: Allow for writing to a vec<u64> instead of a file

### ISSUE THREAD

**Issue by twiclo** [thscharler/spreadsheet-ods#23]
I just want to send the generated ODS straight to actix to be served up to my front end user. Having to use the filesystem is unnecessary in this use case. Any possibilities this could be added?

**Comment by thscharler** [comment]
Should not be too complicated.

But the standard seems to be a Vec<u8> for such things?

**Comment by thscharler** [comment]
I added a version of this to 0.8.

**Comment by twiclo** [comment]
Wow thanks for the quick response. I'll test it out later today and let you know how it goes
