### ISSUE TITLE
Unable to open generated ODS in Excel

### ISSUE THREAD

**Issue by twiclo** [thscharler/spreadsheet-ods#24]
When trying to open my ods in excel it gives a file corrupted message. If you open that same ods in LibreOffice then save it under a different name you'll see that LibreOffice adds to the archive. The newly saved archive can be opened in Excel without issue.

Pre-re-saved ods that I generated using the library
[AspenSummit_bom (5).ods](https://github.com/thscharler/spreadsheet-ods/files/6697434/AspenSummit_bom.5.ods)
And the re-saved ods file
[test.ods](https://github.com/thscharler/spreadsheet-ods/files/6697436/test.ods)

**Comment by thscharler** [comment]
I'll have a look. First I have to see to get excel...

**Comment by twiclo** [comment]
Haha can't blame you for not having it

**Comment by thscharler** [comment]
Found the bugger. Online excel stumbled upon the empty content-validations tag. 
And it absolutely needs a sheet-name.

**Comment by thscharler** [comment]
0.8.1 is out. please try

**Comment by twiclo** [comment]
That took care of it. Thanks again for the speedy resolution!

**Comment by thscharler** [comment]
Can't guarantee that next time.
But this one nagged me.
