### ISSUE TITLE
Can't use formatting because the color crate is broken

### ISSUE THREAD

**Issue by Bqleine** [thscharler/spreadsheet-ods#25]
The "color" crate is broken and can't be built, therefore no Rgb struct can be passed to functions needing colors like set_background_color

**Comment by thscharler** [comment]
I will look at this. May take a few days until I find the time.

**Comment by Bqleine** [comment]
thanks!

**Comment by thscharler** [comment]
I updated my dependencies and ran my tests. Seems to be working?

Could you bring some error messages or so.

**Comment by Bqleine** [comment]
Turns out I used the wrong color crate (:skull:). Sorry for bothering you
