### ISSUE TITLE
Output using std::io:Write

### ISSUE THREAD

**Issue by andreas-mausch** [thscharler/spreadsheet-ods#33]
Similar to #23, it would be great if the standard Write trait could be used directly.

**Comment by thscharler** [comment]
For this to work it needs to be Write + Seek. Is this working for you?

**Comment by andreas-mausch** [comment]
Yes, Write and Seek works fine for me.

**Comment by thscharler** [comment]
Ok, then I pack it into 0.16 too.

**Comment by thscharler** [comment]
done
