### ISSUE TITLE
Formatting: negative numbers in red

### ISSUE THREAD

**Issue by andreas-mausch** [thscharler/spreadsheet-ods#34]
It would be great to have an option for a different formatting if a number value is negative.

![image](https://github.com/thscharler/spreadsheet-ods/assets/1736847/ab89ebc1-31ae-4411-bc91-dd9658e5c64f)

Here is an example in Kotlin using `odfdom`:
https://github.com/andreas-mausch/haspa-camt052-to-csv/blob/00097d577ec02b09020007a1cbcdb37374ce3d18/haspa-parser.kts#L234-L257

**Comment by thscharler** [comment]
I think it should be possible.  Will look into it at the weekend.

**Comment by thscharler** [comment]
I add example/negative_number_red.rs with a solution. 

I'm publishing 0.16 for this, because of course there still was a bug.

**Comment by thscharler** [comment]
done
