### ISSUE TITLE
Re-export color crate

### ISSUE THREAD

**Issue by Shatur** [thscharler/spreadsheet-ods#35]
Could you re-export color crate to allow users to use it without specifying it explicitly in `Cargo.toml`?
Sometimes users can be confused, see https://github.com/thscharler/spreadsheet-ods/issues/25.

**Comment by thscharler** [comment]
I will see to this and your other issues in the next few days.

**Comment by Shatur** [comment]
@thscharler no problem, take your time. I opened PRs to address them.

**Comment by thscharler** [comment]
Will add this, but slightly different to your PR.
