### ISSUE TITLE
req: Basic support for .fods files

### ISSUE THREAD

**Issue by cornmonger** [thscharler/spreadsheet-ods#46]
Would it be possible to add support for flat ODS files that are not zipped?

When using ODS files as assets in Git projects, it can be useful to save them in their unzipped format so that Git can properly diff the files and track changes. Even very basic support, without regard to complex manifests, would be highly useful here.

**Comment by thscharler** [comment]
I have not looked very deep into this topic, so I'm not sure how much of the parsing/writing logic could be reused.

**Comment by thscharler** [comment]
Hm, it seems doable.
Would only need new entry functions and a new layer to put it all in one file.

It will be trickier to get the same XML format as LibreOffice writes, in order to get usefull diffs. 
And I don't know about other writers at all. So depending on your workflow you might get
a lot of garbage in your diffs.

**Comment by cornmonger** [comment]
That's good to hear!

The two workflows that I'm working with either use LibreOffice to write and this crate to read or vice versa. In those cases, it wouldn't matter if output didn't match LibreOffice line-for-line. I think that even if I had a workflow that went back and forth with writing, extra diffs would still be an improvement. Currently, I have to use a bash script that uses LibreOffice to `--convert-to` the appropriate format.

**Comment by thscharler** [comment]
Well then I will ignore the formatting for now. 

At the moment I'm grabbing random samples from the internet to do some stress testing. 
But afterwards I'll look into this one.

**Comment by cornmonger** [comment]
Thank you!

lmk If you need an extra hand with anything.

**Comment by thscharler** [comment]
I put this on the "fods" branch. 

There are now read/write_*f*ods() functions for this.

If you would give it at try.

**Comment by cornmonger** [comment]
I've tried out the new read_fods() and write_fods() functions in some of the workflows this morning and they're both working great so far. Thank you again!

**Comment by thscharler** [comment]
good. I will publish a new version sometime this week including this.
