### ISSUE TITLE
method  `unescape_value`  for struct `quick_xml::events::attributes::Attribute`  is only available if  `encoding`  feature is disabled

### ISSUE THREAD

**Issue by sebmiq** [thscharler/spreadsheet-ods#47]
Hi,

See https://docs.rs/quick-xml/latest/quick_xml/events/attributes/struct.Attribute.html

If another dependency uses the `encoding` feature of `quick_xml`, `spreadsheet-ods` fails to build.

**Comment by thscharler** [comment]
Ok, I'll have a look at it.

**Comment by thscharler** [comment]
fixed in 0.20.2
