### ISSUE TITLE
Error 508 when setting a formula

### ISSUE THREAD

**Issue by Shatur** [thscharler/spreadsheet-ods#48]
When I try to set the following formula: `MAX(-MIN({start_cell}:{end_cell}),MAX({start_cell}:{end_cell}))` (where `start_cell` and `end_cell` are my variables with cell names) it results in `Err:508` in the cell.
But when I edit such formula in LibreOffice (by adding a space after comma, for example), it starting to work. If I undo the change (remove a space to make it as before, for example), it also works. I suspect that there might be some problem in the library when you set complex formulas like this.

**Comment by Shatur** [comment]
Looks like it works if I use `;` instead of `,`.
But LibreOffice will display `;` as `,`.

**Comment by thscharler** [comment]
a yes, the internal encoding for some things is fixed, and that is what the library uses.

What is displayed in Calc is customizable.

That's Extras/Options 
in the dialog LibreOffice Calc/Formula

maybe. I use the german version and that's my translation.

There you can set the separators and the display syntax. 
I left everything at the default and checked 'Use english function names' too.

Then it can be copied as is.

**Comment by Shatur** [comment]
Thanks!
