### ISSUE TITLE
`color-rs` causes compilation issues

### ISSUE THREAD

**Issue by Shatur** [thscharler/spreadsheet-ods#49]
The problem described and fixed in https://github.com/arturoc/color-rs/pull/2. But looks like the crate is not actively maintained. Maybe replace it with another crate?

**Comment by thscharler** [comment]
Yes I've seen this too. 

As a quick-fix for my own uses I use a local copy of color-rs for my compilation.

I think I will wait for a few more days if there is any reaction to this. Afterwards
I'm not sure. 

I would prefer not to fork color-rs or to vendor it into spreadsheet-ods, 
and I haven't looked for a replacement yet. 

You got any suggestions for a replacement?

**Comment by mirsella** [comment]
Well, maybe just fork it with the patch and use this version (maybe even from git, no need to publish it) in spreadsheet-ods ? No need to maintain it, just having a single trusted source (you)

**Comment by mirsella** [comment]
The crate maintainer just came back and merge it, and this crate now build without errors ! This issue can be closed

**Comment by mirsella** [comment]
The crate maintainer just merged the fix !

**Comment by thscharler** [comment]
This is not resolved yet, waiting for a release of color-rs.

**Comment by thscharler** [comment]
Fixed with release 0.22.3.

I use `num-traits = "=0.2.18"` which fixes the miscompile of color-rs.
