### ISSUE TITLE
Update `zip` dependency

### ISSUE THREAD

**Issue by Shatur** [thscharler/spreadsheet-ods#50]
I recently updated transitive `flate2` dependency (a dependency of `zip`) and faced slowdown: https://github.com/rust-lang/flate2-rs/issues/395.
I reached to the author of `zip` and looks like he addressed the performance regression in the new version: https://github.com/zip-rs/zip2/issues/138

Could you update `zip` dependency to 1.3?

**Comment by thscharler** [comment]
Sure

**Comment by thscharler** [comment]
Would have fixed this now, but im still blocked on [arturoc/color-rs#2](https://github.com/arturoc/color-rs/pull/2) for the release ...

**Comment by Shatur** [comment]
Thanks, closing.
