### ISSUE TITLE
zip 1.3 has been yanked (dep)

### ISSUE THREAD

**Issue by mirsella** [thscharler/spreadsheet-ods#53]
the latest commit bump zip to 1.3 but this version is not available anymore (https://docs.rs/zip/1.3.0/zip/index.html)

as a result compilation fails

**Comment by mirsella** [comment]
Using 2.1 compile well

**Comment by mirsella** [comment]
Updating to 2.1 works

**Comment by thscharler** [comment]
Fixed with 0.22.3.

And I now explicitly use `num-traits = "=0.2.18"` which fixes the miscompile of `color-rs`
