### ISSUE TITLE
push_rowname and push_colname can overflow

### ISSUE THREAD

**Issue by GNULinuxIsGreat** [thscharler/spreadsheet-ods#6]
### these functions can overflow if the input equal `ucell::MAX`:
```rust 
pub(crate) fn push_colname(buf: &mut String, mut col: ucell);
pub(crate) fn push_rowname(buf: &mut String, mut row: ucell);
```
for example:
```rust
let c = CellRef::local(ucell::MAX, ucell::MAX);
println!("{}", c); //calling Display trait call  push_colname and push_rowname
```
can I rewrite these functions please?

**Comment by GNULinuxIsGreat** [comment]
P.S. can I add for example a discord server for talking(creating an issue each time i have a question is boring)?

**Comment by thscharler** [comment]
sry, was busy with other things. 
I will look over this immedately. 

a discord would be ok, but I've never used this before. 
wouldn't know how to set it up.

**Comment by GNULinuxIsGreat** [comment]
i can try to do the discord server
>a discord would be ok, but I've never used this before.
wouldn't know how to set it up.

**Comment by GNULinuxIsGreat** [comment]
I created the server @thscharler [https://discord.gg/g4VEHZV](https://discord.gg/g4VEHZV)

**Comment by GNULinuxIsGreat** [comment]
oopsi wrong button sry
